### ISSUE TITLE
no source files found matching

### ISSUE THREAD

**Issue by 3719left** [SouthernCD/braker2_singularity#1]
Hi there,

I got this error below which indicated no matching files found. But the actual file is there. I believe singularity was installed correctly. Can you help me figure out?

val@val-X9DAi:/PBIO2/braker2_singularity$ sudo singularity build braker2.sif braker2.def
[sudo] password for val: 
INFO:    Starting build...
Getting image source signatures
Copying blob 22a6fc63b9b5 skipped: already exists  
Copying blob 42c077c10790 skipped: already exists  
Copying blob 1a23c9d790a3 skipped: already exists  
Copying config fc46e48bfe done  
Writing manifest to image destination
Storing signatures
2022/10/06 16:06:14  info unpack layer: sha256:42c077c10790d51b6f75c4eb895cbd4da37558f7215b39cbf64c46b288f89bda
2022/10/06 16:06:16  info unpack layer: sha256:1a23c9d790a34c5bb13dbaf42e0ea2a555e089aefed7fdfa980654f773b39b39
2022/10/06 16:06:20  info unpack layer: sha256:22a6fc63b9b529f00082379be512f0ca1c7a491872396994cf59b47e794c5e09
INFO:    Copying $PWD/gm_key_64.gz to /opt
FATAL:   While performing build: unable to copy files from host to container fs: no source files found matching: $PWD/gm_key_64.gz
val@val-X9DAi:/PBIO2/braker2_singularity$ ls
braker2.def  braker.xyx.pl  gmes_linux_64_4.tar.gz  gm_key_64.gz  LICENSE  prothint.py  README.md  run_spliced_alignment.py
val@val-X9DAi:/PBIO2/braker2_singularity$

**Comment by 3719left** [comment]
I have the gm_key_64.gz file in braker2_singularity folder as you can see the outcome of "ls" command after the error.
I tried comment out "$PWD/gm_key_64.gz /opt" with "#".
Same error happened to "$PWD/gmes_linux_64_4.tar.gz /opt".

**Comment by SouthernCD** [comment]
I have tested this def file in centos environment and there is no problem. Maybe there is something wrong with your $PWD variable setting, I guess. If you can't fix it, maybe you can change the path to the file in the def file to an absolute path.

**Comment by SouthernCD** [comment]
> I have the gm_key_64.gz file in braker2_singularity folder as you can see the outcome of "ls" command after the error.
> I tried comment out "$PWD/gm_key_64.gz /opt" with "#".
> Same error happened to "$PWD/gmes_linux_64_4.tar.gz /opt".

I see it now and it's strange

**Comment by 3719left** [comment]
OK. I will try. Thanks!
